src/CreditCards/ViewModels/NewCreditCardApplicationDetails.cs
using System.ComponentModel.DataAnnotations;

namespace CreditCards.ViewModels
{
    public class NewCreditCardApplicationDetails
    {
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please provide a first name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please provide a last name")]
        public string LastName{ get; set; }

        [Display(Name = "Frequent Flyer Number")]
        [Required(ErrorMessage = "Please provide a frequent flyer number")]
        public string FrequentFlyerNumber { get; set; }

        [Display(Name = "Age (in years)")]
        [Required(ErrorMessage = "Please provide an age in years")]
        [Range(18,int.MaxValue, ErrorMessage = "You must be at least 18 years old")]
        public int? Age { get; set; }

        [Display(Name = "Gross Income")]
        [Required(ErrorMessage = "Please provide your gross income")]        
        public decimal? GrossAnnualIncome { get; set; }
    }
}

src/CreditCards/Controllers/ApplyController.cs
using System.Threading.Tasks;
using CreditCards.Core.Interfaces;
using CreditCards.Core.Model;
using CreditCards.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CreditCards.Controllers
{
    public class ApplyController : Controller
    {
        private readonly ICreditCardApplicationRepository _applicationRepository;

        public ApplyController(ICreditCardApplicationRepository applicationRepository)
        {
            _applicationRepository = applicationRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(NewCreditCardApplicationDetails applicationDetails)
        {
            if (!ModelState.IsValid)
            {
                return View(applicationDetails);
            }

            var creditCardApplication = new CreditCardApplication
            {
                FirstName = applicationDetails.FirstName,
                LastName = applicationDetails.LastName,
                FrequentFlyerNumber = applicationDetails.FrequentFlyerNumber,
                Age = applicationDetails.Age.Value,
                GrossAnnualIncome = applicationDetails.GrossAnnualIncome.Value
            };

			// Not mock-able
			var evaluator=new CreditCardApplicationEvaluator(new FrequentFlyerNumberValidator());
			CreditCardApplicationDecision decision = evaluator.Evaluate(creditCardApplication);
			creditCardApplication.Decision = decision;

            await _applicationRepository.AddAsync(creditCardApplication);

            return View("ApplicationComplete", creditCardApplication);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/CreditCards/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CreditCards.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/CreditCards/Controllers/ValuesController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace CreditCards.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new[] { "value1", "value2" };
        }

        [HttpGet("{id}")]
        public IActionResult Get(int id)
        {
            if (id < 1)
            {
                return BadRequest($"Invalid request for id {id}");
            }

            return Content($"Value {id}");
        }

        [HttpPost("StartJob")]
        public IActionResult StartJob()
        {
            return Ok("Batch Job Started");
        }
    }
}

src/CreditCards/Views/Apply/ApplicationComplete.cshtml
@model CreditCards.Core.Model.CreditCardApplication

@{
    ViewData["Title"] = "Application Complete";
}

<h2>Application Complete</h2>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Application Details
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p>Application Decision</p>
                </div>
                <div class="panel-body" id="decision">
                    @Model.Decision
                </div>
                <div class="panel-heading">
                    <p>Application Reference Number</p>
                </div>
                <div class="panel-body">
                    @Model.Id
                </div>

                <div class="panel-heading">
                    <p>Name</p>
                </div>
                <div class="panel-body">
                    @Model.FirstName @Model.LastName
                </div>

                <div class="panel-heading">
                    <p>Age</p>
                </div>
                <div class="panel-body">
                    @Model.Age
                </div>

                <div class="panel-heading">
                    <p>Gross Annual Income</p>
                </div>
                <div class="panel-body">
                    @Model.GrossAnnualIncome
                </div>
            </div>
        </div>
    </div>
</div>

src/CreditCards/Views/Apply/Index.cshtml
@using System.Security.Cryptography.X509Certificates
@*@using Microsoft.AspNetCore.Razor.Tokenizer.Symbols*@
@model CreditCards.ViewModels.NewCreditCardApplicationDetails

@{
    ViewData["Title"] = "Credit Card Application";
}

<h2>New Credit Card Application</h2>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Application Details
            </div>
            <div class="panel-body">
                @Html.ValidationSummary()
                <form method="post" asp-controller="Apply" asp-action="Index">
                    <fieldset class="form-group">
                        <label asp-for="FirstName"></label>
                        <input asp-for="FirstName" class="form-control" />
                    </fieldset>
                    <fieldset class="form-group">
                        <label asp-for="LastName"></label>
                        <input asp-for="LastName" class="form-control" />
                    </fieldset>
                    <fieldset class="form-group">
                        <label asp-for="FrequentFlyerNumber"></label>
                        <input asp-for="FrequentFlyerNumber" class="form-control" />
                    </fieldset>
                    <fieldset class="form-group">
                        <label asp-for="Age"></label>
                        <input asp-for="Age" class="form-control" />
                    </fieldset>
                    <fieldset class="form-group">
                        <label asp-for="GrossAnnualIncome"></label>
                        <input asp-for="GrossAnnualIncome" class="form-control" />
                    </fieldset>
                    <input id="submitApplication" type="submit" value="Submit Application" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </div>
</div>

src/CreditCards/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/CreditCards/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/CreditCards/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>        
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    New low rate
                    <a class="btn btn-default" asp-area="" asp-controller="Apply" asp-action="Index">Apply Now!</a>             
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Easy application process
                    <a class="btn btn-default" asp-area="" asp-controller="Apply" asp-action="Index">Apply Now!</a> 
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Award winning customer service
                    <a class="btn btn-default" asp-area="" asp-controller="Apply" asp-action="Index">Apply Now!</a> 
                </p>
            </div>
        </div>       
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

src/CreditCards/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CreditCards</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CreditCards</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - CreditCards</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>